In [1]:
import pyvista
import pandas as pd
import numpy as np

In [2]:
points = np.arange(0.01, 0.2, 0.01)

pyVista_res_l2 = pd.DataFrame()
pyVista_res_l2['points'] = points
pyVista_res_l2.set_index('points', inplace = True)

pyVista_sum_l2 = pd.DataFrame()
pyVista_sum_l2['points'] = points
pyVista_sum_l2.set_index('points', inplace = True)

In [3]:
def get_sample_data(path):
    filename = path + '.vtk'
    mesh = pyvista.read(filename)
    mesh.sample_over_line((0, -0.00227, 0.09),(0, 0.00227, 0.09))
    sample = [] 
    for i in points:
         sample.append(mesh.sample_over_line((0, -0.00227, i),(0, 0.00227, i),resolution=15)['U'].max())#resolution=15
    sums=[] 
    for i in points:
         sums.append(mesh.sample_over_line((0, -0.00227, i),(0, 0.00227, i),resolution=15)['U'].sum())#resolution=15
    return sample, sums

In [7]:

files = ['96k_cells_l2','144k_cells_l2','258k_cells_l2','500k_cells_l2']
for i in files:
    pyVista_res_l2[i], pyVista_sum_l2[i]  = get_sample_data('data/'+i)
    
#pyVista_res_l2.drop(['96k_cells'], axis=1, inplace = True)

In [8]:

pyVista_res_l2.tail(10)

        96k_cells_l2  144k_cells_l2  258k_cells_l2  500k_cells_l2
points
0.10        1.052538       1.061900       1.062951       1.066470
0.11        1.052641       1.061992       1.063046       1.066568
0.12        1.052688       1.062039       1.063089       1.066613
0.13        1.052711       1.062059       1.063111       1.066633
0.14        1.052721       1.062069       1.063121       1.066643
0.15        1.052721       1.062069       1.063126       1.066648
0.16        1.052729       1.062077       1.063127       1.066653
0.17        1.052731       1.062074       1.063127       1.066653
0.18        1.052729       1.062074       1.063128       1.066653
0.19        1.052731       1.062070       1.063129       1.066653

In [9]:
 pyVista_sum_l2.tail(10)

        96k_cells_l2  144k_cells_l2  258k_cells_l2  500k_cells_l2
points
0.10       10.411175      10.558873      10.549753      10.586522
0.11       10.411591      10.559242      10.550138      10.586921
0.12       10.411784      10.559423      10.550318      10.587097
0.13       10.411875      10.559515      10.550403      10.587173
0.14       10.411915      10.559561      10.550444      10.587217
0.15       10.411922      10.559563      10.550461      10.587239
0.16       10.411951      10.559584      10.550467      10.587251
0.17       10.411955      10.559576      10.550467      10.587252
0.18       10.411952      10.559588      10.550469      10.587253
0.19       10.411962      10.559551      10.550486      10.587262

# tolerance 10-9 96k cells

for a timestep 1sec

In [10]:
pyVista_res_l2['96k_tol_10-9'], pyVista_sum_l2['96k_tol_10-9']  = get_sample_data('96k_cells/'+'channel_96k_cells_10000')

In [23]:
pyVista_res_l2.tail(10)

,96k_cells_l2,144k_cells_l2,258k_cells_l2,500k_cells_l2,96k_tol_10-9
points,,,,,
0.10,1.052538,1.061900,1.062951,1.066470,1.052538
0.11,1.052641,1.061992,1.063046,1.066568,1.052641
0.12,1.052688,1.062039,1.063089,1.066613,1.052688
0.13,1.052711,1.062059,1.063111,1.066633,1.052711
0.14,1.052721,1.062069,1.063121,1.066643,1.052721
0.15,1.052721,1.062069,1.063126,1.066648,1.052721
0.16,1.052729,1.062077,1.063127,1.066653,1.052729
0.17,1.052731,1.062074,1.063127,1.066653,1.052731
0.18,1.052729,1.062074,1.063128,1.066653,1.052731
0.19,1.052731,1.062070,1.063129,1.066653,1.052731

In [24]:
pyVista_sum_l2.tail(10)

,96k_cells_l2,144k_cells_l2,258k_cells_l2,500k_cells_l2,96k_tol_10-9
points,,,,,
0.10,10.411175,10.558873,10.549753,10.586522,10.411175
0.11,10.411591,10.559242,10.550138,10.586921,10.411591
0.12,10.411784,10.559423,10.550318,10.587097,10.411784
0.13,10.411875,10.559515,10.550403,10.587173,10.411875
0.14,10.411915,10.559561,10.550444,10.587217,10.411915
0.15,10.411922,10.559563,10.550461,10.587239,10.411921
0.16,10.411951,10.559584,10.550467,10.587251,10.411951
0.17,10.411955,10.559576,10.550467,10.587252,10.411955
0.18,10.411952,10.559588,10.550469,10.587253,10.411957
0.19,10.411962,10.559551,10.550486,10.587262,10.411963

In [30]:
# check if data changing overtime 

res_l2 = pd.DataFrame()
res_l2['points'] = points
res_l2.set_index('points', inplace = True)

sum_l2 = pd.DataFrame()
sum_l2['points'] = points
sum_l2.set_index('points', inplace = True)

'0'

In [32]:
names = np.arange(0, 10001, 1000)

for i in names:
    name = 'channel_96k_cells_'+str(i)
    res_l2[str(i)], sum_l2[str(i)]  = get_sample_data('96k_cells/'+name)
    
#pyVista_res_l2.drop(['96k_cells'], axis=1, inplace = True)

channel_96k_cells_0
channel_96k_cells_1000
channel_96k_cells_2000
channel_96k_cells_3000
channel_96k_cells_4000
channel_96k_cells_5000
channel_96k_cells_6000
channel_96k_cells_7000
channel_96k_cells_8000
channel_96k_cells_9000
channel_96k_cells_10000

In [33]:
 res_l2

,0,1000,2000,3000,4000,5000,6000,7000,8000,9000,10000
points,,,,,,,,,,,
0.01,0.521646,0.855280,0.855280,0.855280,0.855280,0.855280,0.855280,0.855280,0.855280,0.855280,0.855280
0.02,0.521646,0.966795,0.966795,0.966795,0.966795,0.966795,0.966795,0.966795,0.966795,0.966795,0.966795
0.03,0.521646,1.013855,1.013855,1.013855,1.013855,1.013855,1.013855,1.013855,1.013855,1.013855,1.013855
0.04,0.521646,1.034796,1.034796,1.034796,1.034796,1.034796,1.034796,1.034796,1.034796,1.034796,1.034796
0.05,0.521646,1.044373,1.044373,1.044373,1.044373,1.044373,1.044373,1.044373,1.044373,1.044373,1.044373
0.06,0.521646,1.048821,1.048821,1.048821,1.048821,1.048821,1.048821,1.048821,1.048821,1.048821,1.048821
0.07,0.521646,1.050902,1.050896,1.050896,1.050896,1.050896,1.050896,1.050896,1.050896,1.050896,1.050896
0.08,0.521646,1.051787,1.051870,1.051870,1.051870,1.051870,1.051870,1.051870,1.051870,1.051870,1.051870
0.09,0.521646,1.051890,1.052325,1.052325,1.052325,1.052325,1.052325,1.052325,1.052325,1.052325,1.052325
0.10,0.521646,1.051891,1.052538,1.052538,1.052538,1.052538,1.052538,1.052538,1.052538,1.052538,1.052538
0.11,0.521646,1.051891,1.052641,1.052641,1.052641,1.052641,1.052641,1.052641,1.052641,1.052641,1.052641
0.12,0.521646,1.051891,1.052688,1.052688,1.052688,1.052688,1.052688,1.052688,1.052688,1.052688,1.052688
0.13,0.521646,1.051891,1.052711,1.052711,1.052711,1.052711,1.052711,1.052711,1.052711,1.052711,1.052711
0.14,0.521646,1.051891,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721
0.15,0.521646,1.051891,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721,1.052721
0.16,0.521646,1.051891,1.052729,1.052729,1.052729,1.052729,1.052729,1.052729,1.052729,1.052729,1.052729
0.17,0.521646,1.051891,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731
0.18,0.521646,1.051890,1.052729,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731
0.19,0.521646,1.051890,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731,1.052731

# We can see that after 0.3 sec calculation solution actually not changing.

In [35]:
names = ['96k','144k','258k','500k']


res_tol_9 = pd.DataFrame()
res_tol_9['points'] = points
res_tol_9.set_index('points', inplace = True)

sum_tol_9 = pd.DataFrame()
sum_tol_9['points'] = points
sum_tol_9.set_index('points', inplace = True)

for i in names:
    name = 'channel_'+i+ '_cells_5000'
    res_tol_9[i], sum_tol_9[i]  = get_sample_data('data/tol10-9/'+name)

In [36]:
res_tol_9.tail()

             96k      144k      258k      500k
points
0.15    1.052721  1.062069  1.063126  1.066648
0.16    1.052729  1.062074  1.063127  1.066653
0.17    1.052731  1.062074  1.063127  1.066653
0.18    1.052731  1.062074  1.063128  1.066653
0.19    1.052731  1.062070  1.063129  1.066653

In [39]:
pyVista_res_l2

,96k_cells_l2,144k_cells_l2,258k_cells_l2,500k_cells_l2,96k_tol_10-9
points,,,,,
0.01,0.855280,0.862222,0.857782,0.853530,0.855280
0.02,0.966795,0.975663,0.974700,0.975090,0.966795
0.03,1.013855,1.023350,1.023605,1.025833,1.013855
0.04,1.034796,1.044384,1.045102,1.048079,1.034796
0.05,1.044373,1.053915,1.054828,1.058115,1.044373
0.06,1.048821,1.058296,1.059289,1.062710,1.048821
0.07,1.050896,1.060319,1.061350,1.064829,1.050896
0.08,1.051870,1.061259,1.062303,1.065810,1.051870
0.09,1.052325,1.061694,1.062746,1.066262,1.052325
0.10,1.052538,1.061900,1.062951,1.066470,1.052538
0.11,1.052641,1.061992,1.063046,1.066568,1.052641
0.12,1.052688,1.062039,1.063089,1.066613,1.052688
0.13,1.052711,1.062059,1.063111,1.066633,1.052711
0.14,1.052721,1.062069,1.063121,1.066643,1.052721
0.15,1.052721,1.062069,1.063126,1.066648,1.052721
0.16,1.052729,1.062077,1.063127,1.066653,1.052729
0.17,1.052731,1.062074,1.063127,1.066653,1.052731
0.18,1.052729,1.062074,1.063128,1.066653,1.052731
0.19,1.052731,1.062070,1.063129,1.066653,1.052731

In [38]:
sum_tol_9.tail()

              96k       144k       258k       500k
points
0.15    10.411921  10.559560  10.550462  10.587238
0.16    10.411951  10.559574  10.550470  10.587250
0.17    10.411955  10.559575  10.550469  10.587250
0.18    10.411957  10.559587  10.550471  10.587250
0.19    10.411963  10.559552  10.550490  10.587256

# As we can see tolerance not affect the result, but takes more computational time.
If we will look at sum we can see that there is no consistency only for the simulation with 500k cells