In [45]:
import pyvista
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
points = np.arange(0.01, 0.2, 0.01)

pyVista_res_l2 = pd.DataFrame()
pyVista_res_l2['points'] = points
pyVista_res_l2.set_index('points', inplace = True)

pyVista_sum_l2 = pd.DataFrame()
pyVista_sum_l2['points'] = points
pyVista_sum_l2.set_index('points', inplace = True)

In [3]:
def get_sample_data(path):
    filename = path + '.vtk'
    mesh = pyvista.read(filename)
    mesh.sample_over_line((0, -0.00227, 0.09),(0, 0.00227, 0.09))
    sample = [] 
    for i in points:
         sample.append(mesh.sample_over_line((0, -0.00227, i),(0, 0.00227, i),resolution=15)['U'].max())#resolution=15
    sums=[] 
    for i in points:
         sums.append(mesh.sample_over_line((0, -0.00227, i),(0, 0.00227, i),resolution=15)['U'].sum())#resolution=15
    return sample, sums

In [6]:
files =['16k_cells','57k_cells','194k_cells','460k_cells','656k_cells']

#/home/asa/Desktop/OldReposOfFDA_collab/FDA-collaboration/verification/
for i in files:
    pyVista_res_l2[i], pyVista_sum_l2[i]  = get_sample_data('data/ri_extr/channel_'+i)

In [7]:
pyVista_res_l2.tail(10)

        16k_cells  57k_cells  194k_cells  460k_cells  656k_cells
points
0.10     1.033854   1.049109    1.061323    1.066210    1.067629
0.11     1.033956   1.049207    1.061423    1.066308    1.067727
0.12     1.034003   1.049255    1.061469    1.066353    1.067771
0.13     1.034029   1.049275    1.061489    1.066373    1.067793
0.14     1.034041   1.049285    1.061499    1.066383    1.067803
0.15     1.034041   1.049292    1.061503    1.066388    1.067806
0.16     1.034050   1.049292    1.061503    1.066393    1.067806
0.17     1.034050   1.049292    1.061509    1.066393    1.067806
0.18     1.034050   1.049292    1.061509    1.066393    1.067811
0.19     1.034050   1.049292    1.061509    1.066393    1.067811

In [8]:
 pyVista_sum_l2.tail(10)

        16k_cells  57k_cells  194k_cells  460k_cells  656k_cells
points
0.10    10.304304  10.431689   10.547749   10.582661   10.597792
0.11    10.304751  10.432094   10.548152   10.583055   10.598188
0.12    10.304956  10.432295   10.548340   10.583241   10.598364
0.13    10.305065  10.432384   10.548412   10.583321   10.598454
0.14    10.305114  10.432430   10.548460   10.583357   10.598488
0.15    10.305121  10.432451   10.548475   10.583380   10.598507
0.16    10.305154  10.432451   10.548493   10.583388   10.598518
0.17    10.305155  10.432451   10.548507   10.583389   10.598519
0.18    10.305156  10.432451   10.548506   10.583389   10.598529
0.19    10.305158  10.432451   10.548506   10.583389   10.598528

# tolerance 10-9 96k cells

for a timestep 1sec

In [9]:
pyVista_tol_10_9 = pd.DataFrame()
pyVista_tol_10_9['points'] = points
pyVista_tol_10_9.set_index('points', inplace = True)

pyVista_sum_tol_10_9 = pd.DataFrame()
pyVista_sum_tol_10_9['points'] = points
pyVista_sum_tol_10_9.set_index('points', inplace = True)

In [12]:
for i in files:
    pyVista_tol_10_9[i], pyVista_sum_tol_10_9[i]  = get_sample_data('/data/tol10-9/channel_'+i)

In [13]:
pyVista_tol_10_9.tail(10)

        16k_cells  57k_cells  194k_cells  460k_cells  656k_cells
points
0.10     1.033854   1.049109    1.061323    1.066210    1.067629
0.11     1.033956   1.049207    1.061423    1.066308    1.067727
0.12     1.034003   1.049255    1.061469    1.066353    1.067771
0.13     1.034029   1.049275    1.061489    1.066373    1.067793
0.14     1.034041   1.049285    1.061499    1.066383    1.067803
0.15     1.034041   1.049292    1.061503    1.066388    1.067806
0.16     1.034050   1.049292    1.061503    1.066393    1.067806
0.17     1.034050   1.049292    1.061509    1.066393    1.067806
0.18     1.034050   1.049292    1.061509    1.066393    1.067811
0.19     1.034050   1.049292    1.061509    1.066393    1.067811

In [14]:
pyVista_sum_tol_10_9.tail(10)

        16k_cells  57k_cells  194k_cells  460k_cells  656k_cells
points
0.10    10.304304  10.431689   10.547749   10.582661   10.597792
0.11    10.304751  10.432093   10.548152   10.583055   10.598188
0.12    10.304956  10.432295   10.548340   10.583241   10.598364
0.13    10.305065  10.432384   10.548412   10.583321   10.598454
0.14    10.305114  10.432430   10.548460   10.583357   10.598488
0.15    10.305121  10.432451   10.548475   10.583380   10.598507
0.16    10.305154  10.432451   10.548493   10.583388   10.598518
0.17    10.305155  10.432451   10.548507   10.583389   10.598519
0.18    10.305156  10.432451   10.548506   10.583389   10.598529
0.19    10.305158  10.432451   10.548506   10.583389   10.598529

In [15]:
# check if data changing overtime 

res_l2 = pd.DataFrame()
res_l2['points'] = points
res_l2.set_index('points', inplace = True)

sum_l2 = pd.DataFrame()
sum_l2['points'] = points
sum_l2.set_index('points', inplace = True)

In [18]:
pyVista_tol_10_9 - pyVista_res_l2

        16k_cells  57k_cells  194k_cells  460k_cells    656k_cells
points
0.01          0.0        0.0         0.0         0.0  0.000000e+00
0.02          0.0        0.0         0.0         0.0  0.000000e+00
0.03          0.0        0.0         0.0         0.0  0.000000e+00
0.04          0.0        0.0         0.0         0.0  0.000000e+00
0.05          0.0        0.0         0.0         0.0  0.000000e+00
0.06          0.0        0.0         0.0         0.0  0.000000e+00
0.07          0.0        0.0         0.0         0.0  0.000000e+00
0.08          0.0        0.0         0.0         0.0  0.000000e+00
0.09          0.0        0.0         0.0         0.0  0.000000e+00
0.10          0.0        0.0         0.0         0.0  0.000000e+00
0.11          0.0        0.0         0.0         0.0  0.000000e+00
0.12          0.0        0.0         0.0         0.0  0.000000e+00
0.13          0.0        0.0         0.0         0.0  0.000000e+00
0.14          0.0        0.0         0.0         0.0  0.000000e+00
0.15          0.0        0.0         0.0         0.0  0.000000e+00
0.16          0.0        0.0         0.0         0.0  0.000000e+00
0.17          0.0        0.0         0.0         0.0  0.000000e+00
0.18          0.0        0.0         0.0         0.0  0.000000e+00
0.19          0.0        0.0         0.0         0.0  5.960464e-07

# We can see that after 0.3 sec calculation solution actually not changing.

In [40]:
time = np.arange(0,1.1,0.1)

time_diff = pd.DataFrame()
time_diff['time'] =points
time_diff.set_index('time', inplace = True)

sum_time_diff = pd.DataFrame()
sum_time_diff['time'] = points
sum_time_diff.set_index('time', inplace = True)

for i in time:
    name = 'channel_'+'57k'+ '_cells_'+str(int(i*10000))
    time_diff[i], sum_time_diff[i] = get_sample_data('/data/57k_cells_case/'+name)

In [49]:
time_diff

,0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0
time,,,,,,,,,,,
0.01,0.521646,0.857517,0.857517,0.857517,0.857517,0.857517,0.857517,0.857517,0.857517,0.857517,0.857517
0.02,0.521646,0.965655,0.965655,0.965655,0.965655,0.965655,0.965655,0.965655,0.965655,0.965655,0.965655
0.03,0.521646,1.011370,1.011370,1.011370,1.011370,1.011370,1.011370,1.011370,1.011370,1.011370,1.011370
0.04,0.521646,1.031759,1.031759,1.031759,1.031759,1.031759,1.031759,1.031759,1.031759,1.031759,1.031759
0.05,0.521646,1.041111,1.041111,1.041111,1.041111,1.041111,1.041111,1.041111,1.041111,1.041111,1.041111
0.06,0.521646,1.045458,1.045458,1.045458,1.045458,1.045458,1.045458,1.045458,1.045458,1.045458,1.045458
0.07,0.521646,1.047501,1.047492,1.047492,1.047492,1.047492,1.047492,1.047492,1.047492,1.047492,1.047492
0.08,0.521646,1.048363,1.048448,1.048448,1.048448,1.048448,1.048448,1.048448,1.048448,1.048448,1.048448
0.09,0.521646,1.048465,1.048895,1.048895,1.048895,1.048895,1.048895,1.048895,1.048895,1.048895,1.048895
0.10,0.521646,1.048467,1.049109,1.049109,1.049109,1.049109,1.049109,1.049109,1.049109,1.049109,1.049109
0.11,0.521646,1.048467,1.049207,1.049207,1.049207,1.049207,1.049207,1.049207,1.049207,1.049207,1.049207
0.12,0.521646,1.048467,1.049255,1.049255,1.049255,1.049255,1.049255,1.049255,1.049255,1.049255,1.049255
0.13,0.521646,1.048467,1.049275,1.049275,1.049275,1.049275,1.049275,1.049275,1.049275,1.049275,1.049275
0.14,0.521646,1.048467,1.049285,1.049285,1.049285,1.049285,1.049285,1.049285,1.049285,1.049285,1.049285
0.15,0.521646,1.048467,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292
0.16,0.521646,1.048467,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292
0.17,0.521646,1.048467,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292
0.18,0.521646,1.048467,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292
0.19,0.521646,1.048467,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292,1.049292

In [51]:
#difference between columns
time_diff.diff(axis =1)

      0.0       0.1       0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.0
time
0.01  NaN  0.335871  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.02  NaN  0.444009  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.03  NaN  0.489724  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.04  NaN  0.510113  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.05  NaN  0.519465  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.06  NaN  0.523812  0.000000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.07  NaN  0.525855 -0.000009  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.08  NaN  0.526717  0.000085  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.09  NaN  0.526819  0.000430  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.10  NaN  0.526821  0.000641  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.11  NaN  0.526821  0.000740  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.12  NaN  0.526821  0.000787  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.13  NaN  0.526821  0.000807  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.14  NaN  0.526821  0.000817  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.15  NaN  0.526821  0.000825  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.16  NaN  0.526821  0.000825  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.17  NaN  0.526821  0.000825  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.18  NaN  0.526821  0.000825  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
0.19  NaN  0.526821  0.000825  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

# As we can see tolerance not affect the result, but takes more computational time.
If we will look at sum we can see that there is no consistency only for the simulation with 500k cells